version: "3.8"
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./code:/code
      - ./site.conf:/ect/nginx/conf.d/site.conf
    links:
      - php_nastushka
  php_nastushka:
    image: php:8.3-fpm
    volumes:
      - ./code:/code